# Generated by Django 4.1.3 on 2022-11-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150, verbose_name='title_en')),
                ('title_ja', models.CharField(max_length=150, verbose_name='title_ja')),
                ('text_en', models.TextField(blank=True, verbose_name='text_en')),
                ('text_ja', models.TextField(blank=True, verbose_name='text_ja')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='create_day')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='update_day')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.category', verbose_name='category')),
            ],
        ),
    ]
